[package]
name = "codspeed-test"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
codspeed-criterion-compat = "2.6.0"
criterion = "0.5.1"

[[bench]]
name = "fibonacci"
harness = false
